"""Auto migration

Revision ID: c495e19f6875
Revises: 
Create Date: 2025-06-27 23:02:23.724652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c495e19f6875"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("certificate", schema=None) as batch_op:
        batch_op.add_column(sa.Column("link", sa.String(length=120), nullable=True))
        batch_op.drop_column("image_path")

    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.add_column(sa.Column("git_link", sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_column("git_link")

    with op.batch_alter_table("certificate", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("image_path", sa.VARCHAR(length=120), nullable=True)
        )
        batch_op.drop_column("link")

    # ### end Alembic commands ###
