"""Initial migration

Revision ID: d45594104c0e
Revises:
Create Date: 2025-10-06 15:26:32.697800

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d45594104c0e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "admin_user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "certificate",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("issuer", sa.String(length=100), nullable=True),
        sa.Column("skills", sa.String(length=200), nullable=True),
        sa.Column("link", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "contact_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("short_description", sa.String(length=300), nullable=True),
        sa.Column("long_description", sa.Text(), nullable=True),
        sa.Column("image_path", sa.String(length=120), nullable=True),
        sa.Column("stack", sa.String(length=200), nullable=True),
        sa.Column("link_type", sa.String(length=20), nullable=True),
        sa.Column("git_link", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug", name="uq_project_slug"),
    )
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_project_slug"), ["slug"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("project", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_project_slug"))

    op.drop_table("project")
    op.drop_table("contact_message")
    op.drop_table("certificate")
    op.drop_table("admin_user")
    # ### end Alembic commands ###
